FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev --only-group weather --no-install-project

ENV PATH="/app/.venv/bin:$PATH"

COPY run_weather_mcp_server.py .

EXPOSE 8001

CMD ["python", "run_weather_mcp_server.py"]

