FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir onnxruntime transformers

COPY model_optimized.onnx /app/

COPY tokenizer/ /app/tokenizer/

COPY inference_onnx.py /app/

EXPOSE 8000

CMD ["python", "inference_onnx.py"]